classDiagram
    class login {
        -correo: string
        -password: string
    }

    class menu {
        -menu:  link button
        -estudiante: link button
        -curso: link button
        -profesor: link button
        -contacto: link button
        -salir: link button
    }
    class estudiante {
        -id_estudiante: int
        -nombre: string
        -apellido: string
        -carrera: string
        -correo: string
    }

    class curso {
        -codigo: string
        -nombre: string
        -creditos_ int 
    }

    class profesor {
        -id_profesor: int 
        -nombre: string
        -apellido: string
        -especialidad: string
        -correo: string
    }

    class contacto {
        -nombre: string
        -correo: string
        -asunto: string
        -mensaje: string
    }
    class salir{
        -salir: link button
    }

    login "estudiante" --> menu: ingresa
    login "profesor" --> menu: ingresa
    menu "estudiante" --> estudiante
    menu "profesor" --> profesor
    estudiante "*" --> curso: puede matricular
    profesor "*" --> curso: puede impartir
    curso "*" --> contacto
    contacto "1" --> salir
    salir "1" --> login: cierra sesión
    


    

    



